spring:
  profiles:
    active: dev
  mustache.check-template-location: false

logging.level.com.example: debug

HEADERS: Content-Type,Content-Length,Access-Control-Allow-Origin,Content-Encoding,Vary,user-roles,access-token,user-session
METHODS: GET,POST,PUT,OPTIONS,HEADER,DELETE
